name: Check Javascript Vulnerabilities.
description: "Check javascript vulnerabilities to the PR"

inputs:
  frontend_wd: 
    description: "A working directory passed from the caller workflow"
    required: true
  backend_wd: 
    description: "A working directory passed from the caller workflow"
    required: true
  config_file:
    description: "A working directory passed from the caller workflow"
    default: "audit-ci.json"
    required: false
  node_version:
    description: "The version of nodejs to use, defaults to `14`."
    default: "14"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

    - if: inputs.frontend_wd == 'frontend_wd'
      shell: bash
      working-directory: ${{ inputs.frontend_wd }}
      run: npx audit-ci --config ${{ inputs.config_file }}
       
    - if: inputs.backend_wd == 'backend_wd'
      shell: bash
      working-directory: ${{ inputs.backend_wd }}
      run: npx audit-ci --config ${{ inputs.config_file }}
           
