name: Check Javascript Vulnerabilities.
description: "Check javascript vulnerabilities to the PR"

inputs:
  frontend_wd: 
    description: "A working directory passed from the caller workflow"
    required: true
  backend_wd: 
    description: "A working directory passed from the caller workflow"
    required: true
  config_file:
    description: "A working directory passed from the caller workflow"
    default: "audit-ci.json"
    required: false
  node_version:
    description: "The version of nodejs to use, defaults to `14`."
    default: "14"
    required: false
    
outputs:
  js_vulns_frontend:
    description: Return true only when any files that match input files_to_match pattern have changed.
    value: ${{ steps.frontend.outputs.frontend_wd }}
  js_vulns_backend:
    description: Return true only when any files that match input files_to_match pattern have changed.
    value: ${{ steps.backend.outputs.backend_wd }}

runs:
  using: "composite"
  steps:
    - name: Install Node.js ${{ inputs.node_version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.node_version }}

    - name: Check Javascript Vulnerabilities for frontend.
      id: frontend
      shell: bash
      working-directory: ${{ inputs.frontend_wd }}
      run: echo "::set-output name=frontend_wd::$(npx audit-ci --config ${{ inputs.config_file }})"

    - name: Check Javascript Vulnerabilities for backend.
      id: backend
      shell: bash
      working-directory: ${{ inputs.backend_wd }}
      run: echo "::set-output name=backend_wd::$(npx audit-ci --config ${{ inputs.config_file }})"
           
