name: Permissions Advisor

# permissions:
#   actions: read

on:
  workflow_call:
    inputs:
      files:
        description: 'Comma-separated list of workflow files to analyze'
        required: false
        type: string
        default: |
         test-actions.yaml,
         go-releas.yaml
         
      count:
        description: 'How many last runs to analyze'
        required: false
        type: string
        default: "2"

jobs:
  advisor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        files: ${{ fromJson(inputs.files) }}
        
    steps:
    - name: Run Advisor for each file
      uses: actions/checkout@v2
 
    - uses: GitHubSecurityLab/actions-permissions/advisor@v1
      with:
        name: ${{ matrix.files }}
        count: ${{ fromJSON(inputs.count) }}
