name: Permissions Advisor

# permissions:
#   actions: read

on:
  workflow_call:
    inputs:
      files:
        description: 'Comma-separated list of workflow files to analyze'
        required: true
        type: string

      count:
        description: 'How many last runs to analyze'
        required: false
        type: string
        default: "2"

jobs:
  advisor:
    runs-on: ubuntu-latest

    steps:
    - uses: GitHubSecurityLab/actions-permissions/monitor@v1
    - name: Run Advisor for each file
      uses: actions/checkout@v2
 
    - uses: GitHubSecurityLab/actions-permissions/advisor@v1
      with:
        name: ${{ inputs.files }}
        count: ${{ fromJSON(inputs.count) }}
