name: Reusable workflow for javascript lint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: (^|\/)yarn\.lock$
      config_file:
         required: false
         type: string
         default: "audit-ci.json"
         description: "Set config file to audit the js vulnerabilities"
      frontend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
      backend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true

jobs:
  changed_js_files_job:
    runs-on: ubuntu-latest
    outputs:
      frontend: ${{ steps.filter.outputs.frontend }}
      backend: ${{ steps.filter.outputs.backend }}
      any_changed: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: saiteja-organization/github-actions
        path: github-actions
        ref: td-app-server
        token: ${{ secrets.gh_repo_read_token }}   
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        base: ${{ github.ref }}
        filters: |
          frontend: ${{ inputs.frontend_dir }}/${{ inputs.files_to_match }}
          backend: ${{ inputs.backend_dir }}/${{ inputs.files_to_match }}


  audit_ci_frontend_job:
    runs-on: ubuntu-latest
    needs: changed_js_files_job
    if: needs.changed_js_files_job.outputs.any_changed == 'true'
    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: saiteja-organization/github-actions
          path: github-actions
          ref: td-app-server
          token: ${{ secrets.gh_token }}       

      - name: Check js vulnerabilities for frontend
        if: needs.changed_js_files_job.outputs.frontend == 'true' 
        id: check-javascript-lint1
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_dir: ${{ inputs.frontend_dir }}
          config_file: ${{ inputs.config_file }}

      - name: Check js vulnerabilities for backend
        if: needs.changed_js_files_job.outputs.backend == 'true' 
        id: check-javascript-lint2
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_dir: ${{ inputs.backend_dir }}
          config_file: ${{ inputs.config_file }}
          
