name: Reusable workflow for javascript lint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: (^|\/)yarn\.lock$
      config_file:
         required: false
         type: string
         default: "audit-ci.json"
         description: "Set config file to audit the js vulnerabilities"
      working_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true

jobs:
  changed_js_files_job:
    runs-on: ubuntu-latest
    outputs:
      changed_files: ${{ steps.changed-files.outputs.changed_files }}
      any_changed: ${{ steps.changed-files.outputs.any_changed }}
      working_dir: ${{ steps.set-matrix.outputs.working_dir }}
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: saiteja-organization/github-actions
        path: github-actions
        ref: td-app-server
        token: ${{ secrets.gh_token }}
        
    - id: set-matrix
      run: |
        echo "::set-output name=working_dir::[${{ inputs.frontend_dir }},${{ inputs.backend_dir }}]"

    - name: Get changed javascript files
      id: changed-files
      uses: ./github-actions/.github/actions/changed-files-since-last-success
      with:
        files_to_match: ${{ matrix.working_dir }}\/${{ inputs.files_to_match }}
        github_token: ${{ secrets.gh_token }}
        workflow_id: ${{ inputs.workflow_id }}
        
    - name: test
      run: |
          echo ${{ steps.changed-files.outputs.all_changed_files }}
          ls -lrt ${{ steps.changed-files.outputs.all_changed_files }}
          pwd

    - name: Check js vulnerabilities for ${{ matrix.working_dir }}
      id: check-javascript-lint1
      if: ${{ steps.changed-files.outputs.all_changed_files }} == 'app/yarn.lock'
      uses: ./github-actions/.github/actions/javascript-lint
      with:
        working_dir: ${{ matrix.working_dir }}
        config_file: ${{ inputs.config_file }}
