name: Reusable workflow for javascript lint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: (^|\/)yarn\.lock$
      config_file:
         required: false
         type: string
         default: "audit-ci.json"
         description: "Set config file to audit the js vulnerabilities"
      frontend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
      backend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true

jobs:
  changed_js_files_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 0

    - name: Checkout actions repo
      uses: actions/checkout@v2
      with:
        repository: saiteja-organization/github-actions
        path: github-actions
        ref: td-app-server
        token: ${{ secrets.gh_repo_read_token }}   
    
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend: ${{ inputs.frontend_dir }}/${{ inputs.files_to_match }}
          backend: ${{ inputs.backend_dir }}/${{ inputs.files_to_match }}
    
    - name: Check js vulnerabilities for frontend
      if: steps.filter.outputs.frontend == 'true'
      id: check-javascript-lint1
      uses: ./github-actions/.github/actions/javascript-lint
      with:
        working_dir: ${{ inputs.frontend }}
        config_file: ${{ inputs.config_file }}

    - name: Check js vulnerabilities for backend
      if: steps.filter.outputs.backend == 'true'
      id: check-javascript-lint2
      uses: ./github-actions/.github/actions/javascript-lint
      with:
        working_dir: ${{ inputs.backend }}
        config_file: ${{ inputs.config_file }}
        
