name: Reusable workflow for javascript lint

on:
  workflow_call:
    inputs:
      workflow_id:
         required: true
         type: string
         description: "ID or filename of the workflow to get latest successful commit"
      files_to_match:
         description: "Check for changes using only this list of files or regex (Defaults to the entire repo)"
         required: true
         type: string
         default: yarn\.lock$
      config_file:
         required: false
         type: string
         default: "audit-ci.json"
         description: "Set config file to audit the js vulnerabilities"
      frontend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
      backend_dir: 
         required: true
         type: string
         description: "A working directory passed from the caller workflow" 
    secrets:
      gh_token:
         required:  true
      gh_repo_read_token:
         required:  true

jobs:
  # JOB to run change detection
  changes:
    runs-on: ubuntu-latest
    outputs:
      # Expose matched filters as job 'packages' output variable
      working_dir: ${{ steps.filter.outputs.changes }}
    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          frontend_dir: ${{ matrix.frontend_dir }}/${{ inputs.files_to_match }}
          backend_dir: ${{ matrix.backend_dir }}/${{ inputs.files_to_match }}
          
  audit_ci_job:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        working_dir: ${{ fromJSON(needs.changes.outputs.working_dir) }}
    needs: changes
    if: ${{ needs.changes.outputs.working_dir == 'true' }}
    steps:
      - uses: actions/checkout@v2
        
      - name: Checkout actions repo
        uses: actions/checkout@v2
        with:
          repository: saiteja-organization/github-actions
          path: github-actions
          ref: td-app-server
          token: ${{ secrets.gh_repo_read_token }}       

      - name: Check js vulnerabilities for ${{ inputs.frontend_dir }}
        id: check-javascript-lint1
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_dir: ${{ inputs.frontend_dir }}
          config_file: ${{ inputs.config_file }}

      - name: Check js vulnerabilities for ${{ inputs.frontend_dir }}
        id: check-javascript-lint2
        uses: ./github-actions/.github/actions/javascript-lint
        with:
          working_dir: ${{ inputs.backend_dir }}
          config_file: ${{ inputs.config_file }}
