name: Check Dockerfile Lint rules.

on:
  workflow_call:
   inputs:
    node_install:
       description: "Normally we shouldn't allow lock file updates but during transition from GH to GAR we need this"
       required: false
       type: boolean
       default: false
    test_command:
       description: "Normally we shouldn't allow lock file updates but during transition from GH to GAR we need this"
       required: false
       type: boolean
       default: false    
    yaml_lint:
       description: "Normally we shouldn't allow lock file updates but during transition from GH to GAR we need this"
       required: false
       type: boolean
       default: false    
    config_file:
      description: "Custom rule for yamllint"
      required: false
      type: string
     
jobs:
  test-reusable-gha:
   runs-on: ubuntu-latest
   steps:
    - name: 'Yamllint'
      if: ${{ inputs.yaml_lint }}
      shell: bash
      run: |
        sudo apt install yamllint -y
        exit_code=0
          yamllint -c ${{ inputs.config_file }} $file || exit_code=1
        exit $exit_code
        
    - name: 'node install'
      if: ${{ inputs.node_install }}
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: 'test commands'
      if: ${{ inputs.test_command }}
      run: |
           echo "this is for conditional test final stage"
